language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk7

cache:
  directories:
    - $HOME/.m2

install: true

script: mvn -U -Pci-headless verify

after_success:
  - mvn -Pci-headless clean cobertura:cobertura-integration-test coveralls:report
